#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v
bindkey "^p" up-line-or-search
bindkey "^N" down-line-or-search
bindkey "^R" history-incremental-search-backward

export VISUAL=vim
export EDITOR="$VISUAL"
